name = "pstake-website"
type = "webpack"
zone_id = '6304918b0989e59de2f10ab7af92840a'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-10-08"

[env.staging]
routes = ["https://staging.pstake.finance/*"]

[env.release]
routes = ["https://pstake.finance/*"]
