import React, { useContext } from "react";

import Icon from "../../molecules/Icon";
import Accordion from "../../atoms/accordion/Accordion";

const accordionItems = [
  {
    title: "What is stkDYDX?",
    content:
      "stkDYDX is the liquid staked token issued by pSTAKE Finance on the Persistence One Chain.",
  },
  {
    title:
      "How will pSTAKE distribute my DYDX stake amongst the dYdX validators?",
    content:
      "When DYDX is liquid staked, pSTAKE automatically distributes it to more than 50% of all dYdX chain validators. This feat is achieved with a transparent, on-chain data-driven algorithm focused on dYdX chain decentralization. Validators are selected based on parameters such as voting power, commission, uptime, governance participation, etc. ",
  },
  {
    title: "Why do I get less stkDYDX when I deposit my DYDX?",
    content: (
      <>
        stkDYDX follows a protocol exchange/redemption rate model that defines
        the relationship between stkDYDX and DYDX.
        <br />
        stkDYDX’s value (relative to DYDX) increases daily as DYDX and USDC
        staking rewards are accrued and auto-compounded. 1 stkDYDX tomorrow will
        always be worth more than it is today.
        <br />
        stkDYDX is always minted at the protocol exchange/redemption rate at the
        time of your deposit.
      </>
    ),
  },
  {
    title: "What is the unbonding period for stkDYDX?",
    content:
      "DYDX has an unbonding process of 30 days.\n" +
      "\n" +
      "If regularly unstaked, you can get the respective DYDX tokens back in ~30+ days.\n" +
      "\n" +
      "With stkDYDX, you get the unique option to ‘Flash Unstake’, giving you instant access to DYDX liquidity for a small fee.\n",
  },
  {
    title: "Does pSTAKE charge any fees for DYDX liquid staking?",
    content: (
      <>
        Liquid staking providers charge a certain fee from the staking rewards
        that are generated by total protocol deposits.
        <br />
        The PSTAKE governance has approved a 0% fee on DYDX liquid staking
        (compared to 10% by other providers) initially for two months after
        launch.
      </>
    ),
  },
  {
    title: "Is stkDYDX built using IBC?",
    content: (
      <div>
        stkDYDX is non-custodial and is built using the IBC tech stack on the
        Persistence Core-1 chain, similar to stkATOM. Learn more about it
        <a
          href="https://docs.pstake.finance/stkATOM_Technical_Architecture/"
          target="_blank"
          rel="noopener noreferrer"
          className={"underline"}
        >
          here.
        </a>
      </div>
    ),
  },
  {
    title:
      "How is DYDX liquid staking on pSTAKE different to other Liquid Staking Providers (LSPs)?",
    content: (
      <div>
        stkDYDX brings innovations to the DYDX liquid staking landscape such as
        Flash Unstake, UX improvements like no-click DYDX and USDC staking
        rewards auto-compounding, and a 0% liquid staking fee initially after
        launch. In addition, stkDYDX is custom-built to help decentralize the
        dYdX chain further.
        <a
          href="https://docs.pstake.finance/stkATOM_Technical_Architecture/"
          target="_blank"
          rel="noopener noreferrer"
          className={"underline"}
        >
          here.
        </a>
      </div>
    ),
  },
];

const Faq = () => {
  return (
    <>
      <div id="stkOsmoFaqs" className="bg-[#1C1C28] ">
        <div className="sectionContainer py-[65px] md:py-[35px]">
          <div className="sectionTitle mb-8">
            <h1 className="inline-flex relative">
              FAQ
              <img
                alt="border"
                src={"/images/faq_border.svg"}
                className={"absolute -bottom-[2px]"}
              />
            </h1>
          </div>
          <div className="max-w-[700px] mx-auto">
            <div className="info">
              <Accordion items={accordionItems} />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};
export default Faq;
