import exp from "node:constants";

export interface List {
  [index: string]: any;
}

export const getList = (t: any) => {
  return {
    data_tooling: [
      {
        title: t("ECOSYSTEM_EXPLORE_SKIP_TITLE"),
        logoUrl: "/images/ecosystem/skip.png",
        text: t("ECOSYSTEM_EXPLORE_SKIP_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_SUBQUERY_TITLE"),
        logoUrl: "/images/ecosystem/sub_query.png",
        text: t("ECOSYSTEM_EXPLORE_SUBQUERY_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_CHAIN_LINK_TITLE"),
        logoUrl: "/images/ecosystem/chain_link.png",
        text: t("ECOSYSTEM_EXPLORE_CHAIN_LINK_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_PYTH_TITLE"),
        logoUrl: "/images/ecosystem/pyth.png",
        text: t("ECOSYSTEM_EXPLORE_PYTH_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_COIN_MARKET_CAP_TITLE"),
        logoUrl: "/images/ecosystem/coin_market_cap.png",
        text: t("ECOSYSTEM_EXPLORE_COIN_MARKET_CAP_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_DEX_SCREENER_TITLE"),
        logoUrl: "/images/ecosystem/dex_screener.png",
        text: t("ECOSYSTEM_EXPLORE_DEX_SCREENER_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_CRYPTO_RANK_TITLE"),
        logoUrl: "/images/ecosystem/crypto_rank.png",
        text: t("ECOSYSTEM_EXPLORE_CRYPTO_RANK_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_MEMPOOL_TITLE"),
        logoUrl: "/images/ecosystem/mem_pool.png",
        text: t("ECOSYSTEM_EXPLORE_MEMPOOL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_KYBER_SWAP_TITLE"),
        logoUrl: "/images/ecosystem/kyber_swap.png",
        text: t("ECOSYSTEM_EXPLORE_KYBER_SWAP_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_MATCHA_TITLE"),
        logoUrl: "/images/ecosystem/matcha.png",
        text: t("ECOSYSTEM_EXPLORE_MATCHA_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_COIN_GECKO_TITLE"),
        logoUrl: "/images/ecosystem/coin_gecko.png",
        text: t("ECOSYSTEM_EXPLORE_COIN_GECKO_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_SQUID_TITLE"),
        logoUrl: "/images/ecosystem/squid.png",
        text: t("ECOSYSTEM_EXPLORE_SQUID_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_1INCH_TITLE"),
        logoUrl: "/images/ecosystem/1inch.png",
        text: t("ECOSYSTEM_EXPLORE_1INCH_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_GALXE_TITLE"),
        logoUrl: "/images/ecosystem/galxe.png",
        text: t("ECOSYSTEM_EXPLORE_GALXE_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_COIN_HALL_TITLE"),
        logoUrl: "/images/ecosystem/coin_hall.png",
        text: t("ECOSYSTEM_EXPLORE_COIN_HALL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_LAYER3_TITLE"),
        logoUrl: "/images/ecosystem/layer3.png",
        text: t("ECOSYSTEM_EXPLORE_LAYER3_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_PULSAR_FINANCE_TITLE"),
        logoUrl: "/images/ecosystem/pulsar_finance.png",
        text: t("ECOSYSTEM_EXPLORE_PULSAR_FINANCE_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_TFM_TITLE"),
        logoUrl: "/images/ecosystem/tfm.png",
        text: t("ECOSYSTEM_EXPLORE_TFM_TEXT"),
        link: "/",
      },
    ],
    security: [
      {
        title: t("ECOSYSTEM_EXPLORE_HEXENS_TITLE"),
        logoUrl: "/images/ecosystem/hexens.png",
        text: t("ECOSYSTEM_EXPLORE_HEXENS_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_OAK_TITLE"),
        logoUrl: "/images/ecosystem/oak.png",
        text: t("ECOSYSTEM_EXPLORE_OAK_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_IMMUNEFI_TITLE"),
        logoUrl: "/images/ecosystem/immunefi.png",
        text: t("ECOSYSTEM_EXPLORE_IMMUNEFI_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_FORTA_TITLE"),
        logoUrl: "/images/ecosystem/forta.png",
        text: t("ECOSYSTEM_EXPLORE_FORTA_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_PECK_SHIELD_TITLE"),
        logoUrl: "/images/ecosystem/peck_shield.png",
        text: t("ECOSYSTEM_EXPLORE_PECK_SHIELD_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_SOLIDIFIED_TITLE"),
        logoUrl: "/images/ecosystem/solidified.png",
        text: t("ECOSYSTEM_EXPLORE_SOLIDIFIED_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_NOTIONAL_TITLE"),
        logoUrl: "/images/ecosystem/notional.png",
        text: t("ECOSYSTEM_EXPLORE_NOTIONAL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_HALBORN_TITLE"),
        logoUrl: "/images/ecosystem/hal_born.png",
        text: t("ECOSYSTEM_EXPLORE_HALBORN_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_TRAIL_OF_BITS_TITLE"),
        logoUrl: "/images/ecosystem/trail_of_bits.png",
        text: t("ECOSYSTEM_EXPLORE_TRAIL_OF_BITS_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_CONSENSYS_DILIGENCE_TITLE"),
        logoUrl: "/images/ecosystem/consensys.png",
        text: t("ECOSYSTEM_EXPLORE_CONSENSYS_DILIGENCE_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_CERTORA_TITLE"),
        logoUrl: "/images/ecosystem/certora.png",
        text: t("ECOSYSTEM_EXPLORE_CERTORA_TEXT"),
        link: "/",
      },
    ],
    institutions: [
      {
        title: t("ECOSYSTEM_EXPLORE_COBO_TITLE"),
        logoUrl: "/images/ecosystem/cobo.png",
        text: t("ECOSYSTEM_EXPLORE_COBO_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_EVERSTAKE_TITLE"),
        logoUrl: "/images/ecosystem/everstake.png",
        text: t("ECOSYSTEM_EXPLORE_EVERSTAKE_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_SPARTAN_TITLE"),
        logoUrl: "/images/ecosystem/spartan_group.png",
        text: t("ECOSYSTEM_EXPLORE_SPARTAN_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_DEFINANCE_CAPITAL_TITLE"),
        logoUrl: "/images/ecosystem/definance.png",
        text: t("ECOSYSTEM_EXPLORE_DEFINANCE_CAPITAL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BINANCE_LABS_TITLE"),
        logoUrl: "/images/ecosystem/binance_labs.png",
        text: t("ECOSYSTEM_EXPLORE_BINANCE_LABS_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_ARCANUM_VENTURES_TITLE"),
        logoUrl: "/images/ecosystem/arcanum_ventures.png",
        text: t("ECOSYSTEM_EXPLORE_ARCANUM_VENTURES_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_CEFFU_GLOBAL_TITLE"),
        logoUrl: "/images/ecosystem/ceffu_global.png",
        text: t("ECOSYSTEM_EXPLORE_CEFFU_GLOBAL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_COIN_BASE_VENTURES_TITLE"),
        logoUrl: "/images/ecosystem/coinbase_ventures.png",
        text: t("ECOSYSTEM_EXPLORE_COIN_BASE_VENTURES_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_RYZE_LABS_TITLE"),
        logoUrl: "/images/ecosystem/ryze_labs.png",
        text: t("ECOSYSTEM_EXPLORE_RYZE_LABS_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_KRAKEN_VENTURES_TITLE"),
        logoUrl: "/images/ecosystem/kraken_ventures.png",
        text: t("ECOSYSTEM_EXPLORE_KRAKEN_VENTURES_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_GALAXY_DIGITAL_TITLE"),
        logoUrl: "/images/ecosystem/galaxy_digital.png",
        text: t("ECOSYSTEM_EXPLORE_GALAXY_DIGITAL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_TENDERMINT_TITLE"),
        logoUrl: "/images/ecosystem/tendermint.png",
        text: t("ECOSYSTEM_EXPLORE_TENDERMINT_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_LATTICE_CAPITAL_TITLE"),
        logoUrl: "/images/ecosystem/lattice_capital.png",
        text: t("ECOSYSTEM_EXPLORE_LATTICE_CAPITAL_TEXT"),
        link: "/",
      },
    ],
    exchanges: [
      {
        title: t("ECOSYSTEM_EXPLORE_OKX_TITLE"),
        logoUrl: "/images/ecosystem/okx.png",
        text: t("ECOSYSTEM_EXPLORE_OKX_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_KRAKEN_TITLE"),
        logoUrl: "/images/ecosystem/kraken.png",
        text: t("ECOSYSTEM_EXPLORE_KRAKEN_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_THENA_TITLE"),
        logoUrl: "/images/ecosystem/thena.png",
        text: t("ECOSYSTEM_EXPLORE_THENA_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BIT_MART_TITLE"),
        logoUrl: "/images/ecosystem/bit_mart.png",
        text: t("ECOSYSTEM_EXPLORE_BIT_MART_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_PANCAKESWAP_TITLE"),
        logoUrl: "/images/ecosystem/pancake_swap.png",
        text: t("ECOSYSTEM_EXPLORE_PANCAKESWAP_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BYBIT_TITLE"),
        logoUrl: "/images/ecosystem/bybit.png",
        text: t("ECOSYSTEM_EXPLORE_BYBIT_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_GATE_IO_TITLE"),
        logoUrl: "/images/ecosystem/gate_io.png",
        text: t("ECOSYSTEM_EXPLORE_GATE_IO_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_PERSISTENCE_DEX_TITLE"),
        logoUrl: "/images/ecosystem/persistence_dex.png",
        text: t("ECOSYSTEM_EXPLORE_PERSISTENCE_DEX_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_COINW_TITLE"),
        logoUrl: "/images/ecosystem/coinw.png",
        text: t("ECOSYSTEM_EXPLORE_COINW_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_CRYPTO_COM_TITLE"),
        logoUrl: "/images/ecosystem/crypto_com.png",
        text: t("ECOSYSTEM_EXPLORE_CRYPTO_COM_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_FENIX_TITLE"),
        logoUrl: "/images/ecosystem/fenix.png",
        text: t("ECOSYSTEM_EXPLORE_FENIX_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_MEXC_TITLE"),
        logoUrl: "/images/ecosystem/mexc.png",
        text: t("ECOSYSTEM_EXPLORE_MEXC_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_THRUSTER_TITLE"),
        logoUrl: "/images/ecosystem/thruster.png",
        text: t("ECOSYSTEM_EXPLORE_THRUSTER_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_UNISWAP_TITLE"),
        logoUrl: "/images/ecosystem/uniswap.png",
        text: t("ECOSYSTEM_EXPLORE_UNISWAP_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_COINX_TITLE"),
        logoUrl: "/images/ecosystem/coinx.png",
        text: t("ECOSYSTEM_EXPLORE_COINX_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_KUCOIN_TITLE"),
        logoUrl: "/images/ecosystem/kucoin.png",
        text: t("ECOSYSTEM_EXPLORE_KUCOIN_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_AERODROME_TITLE"),
        logoUrl: "/images/ecosystem/aerodrome.png",
        text: t("ECOSYSTEM_EXPLORE_AERODROME_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_VELODROME_TITLE"),
        logoUrl: "/images/ecosystem/velodrome.png",
        text: t("ECOSYSTEM_EXPLORE_VELODROME_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_OSMOSIS_TITLE"),
        logoUrl: "/images/ecosystem/osmosis.png",
        text: t("ECOSYSTEM_EXPLORE_OSMOSIS_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_XT_TITLE"),
        logoUrl: "/images/ecosystem/xt.png",
        text: t("ECOSYSTEM_EXPLORE_XT_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BITGET_TITLE"),
        logoUrl: "/images/ecosystem/bitget.png",
        text: t("ECOSYSTEM_EXPLORE_BITGET_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BINGX_TITLE"),
        logoUrl: "/images/ecosystem/bingx.png",
        text: t("ECOSYSTEM_EXPLORE_BINGX_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_HTX_TITLE"),
        logoUrl: "/images/ecosystem/htx.png",
        text: t("ECOSYSTEM_EXPLORE_HTX_TEXT"),
        link: "/",
      },
    ],
    wallets: [
      {
        title: t("ECOSYSTEM_EXPLORE_METAMASK_TITLE"),
        logoUrl: "/images/ecosystem/metamask.png",
        text: t("ECOSYSTEM_EXPLORE_METAMASK_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_LEAP_TITLE"),
        logoUrl: "/images/ecosystem/leap.png",
        text: t("ECOSYSTEM_EXPLORE_LEAP_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BINANCE_WEB3_TITLE"),
        logoUrl: "/images/ecosystem/binance_web3.png",
        text: t("ECOSYSTEM_EXPLORE_BINANCE_WEB3_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_TOKEN_POCKET_TITLE"),
        logoUrl: "/images/ecosystem/token_pocket.png",
        text: t("ECOSYSTEM_EXPLORE_TOKEN_POCKET_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_LEDGER_TITLE"),
        logoUrl: "/images/ecosystem/ledger.png",
        text: t("ECOSYSTEM_EXPLORE_LEDGER_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_TRUST_WALLET_TITLE"),
        logoUrl: "/images/ecosystem/trust_wallet.png",
        text: t("ECOSYSTEM_EXPLORE_TRUST_WALLET_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_OKX_WEB3_TITLE"),
        logoUrl: "/images/ecosystem/okx_web3.png",
        text: t("ECOSYSTEM_EXPLORE_OKX_WEB3_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_COIN98_TITLE"),
        logoUrl: "/images/ecosystem/coin_98.png",
        text: t("ECOSYSTEM_EXPLORE_COIN98_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_UNISAT_TITLE"),
        logoUrl: "/images/ecosystem/unisat.png",
        text: t("ECOSYSTEM_EXPLORE_UNISAT_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_WALLET_CONNECT_TITLE"),
        logoUrl: "/images/ecosystem/wallet_connect.png",
        text: t("ECOSYSTEM_EXPLORE_WALLET_CONNECT_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_KEPLR_TITLE"),
        logoUrl: "/images/ecosystem/keplr.png",
        text: t("ECOSYSTEM_EXPLORE_KPELR_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_MATH_WALLET_TITLE"),
        logoUrl: "/images/ecosystem/math_wallet.png",
        text: t("ECOSYSTEM_EXPLORE_MATH_WALLET_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BYBIT_WEB3_TITLE"),
        logoUrl: "/images/ecosystem/bybit.png",
        text: t("ECOSYSTEM_EXPLORE_BYBIT_WEB3_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BIT_GET_TITLE"),
        logoUrl: "/images/ecosystem/bitget.png",
        text: t("ECOSYSTEM_EXPLORE_BIT_GET_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_GATE_WEB3_TITLE"),
        logoUrl: "/images/ecosystem/gate_web3.png",
        text: t("ECOSYSTEM_EXPLORE_GATE_WEB3_TEXT"),
        link: "/",
      },
    ],
    interoperability: [
      {
        title: t("ECOSYSTEM_EXPLORE_IBC_PROTOCOL_TITLE"),
        logoUrl: "/images/ecosystem/ibc_protocol.png",
        text: t("ECOSYSTEM_EXPLORE_IBC_PROTOCOL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_GRAVITY_BRIDGE_TITLE"),
        logoUrl: "/images/ecosystem/gravity_bridge.png",
        text: t("ECOSYSTEM_EXPLORE_GRAVITY_BRIDGE_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_LAYER_ZERO_TITLE"),
        logoUrl: "/images/ecosystem/layer0.png",
        text: t("ECOSYSTEM_EXPLORE_LAYER_ZERO_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_SUPER_BRIDGE_TITLE"),
        logoUrl: "/images/ecosystem/super_bridge.png",
        text: t("ECOSYSTEM_EXPLORE_SUPER_BRIDGE_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_CELER_TITLE"),
        logoUrl: "/images/ecosystem/celer.png",
        text: t("ECOSYSTEM_EXPLORE_CELER_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_AXELAR_TITLE"),
        logoUrl: "/images/ecosystem/axelar.png",
        text: t("ECOSYSTEM_EXPLORE_AXELAR_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BNB_CHAIN_TITLE"),
        logoUrl: "/images/ecosystem/bnb_chain.png",
        text: t("ECOSYSTEM_EXPLORE_BNB_CHAIN_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_LIFI_TITLE"),
        logoUrl: "/images/ecosystem/lifi.png",
        text: t("ECOSYSTEM_EXPLORE_LIFI_TEXT"),
        link: "/",
      },
    ],
    bitcoin_yields: [
      {
        title: t("ECOSYSTEM_EXPLORE_PELL_TITLE"),
        logoUrl: "/images/ecosystem/pell.png",
        text: t("ECOSYSTEM_EXPLORE_PELL_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_SAT_LAYER_TITLE"),
        logoUrl: "/images/ecosystem/sat_layer.png",
        text: t("ECOSYSTEM_EXPLORE_SAT_LAYER_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BABY_LON_TITLE"),
        logoUrl: "/images/ecosystem/baby_lon.png",
        text: t("ECOSYSTEM_EXPLORE_BABY_LON_TEXT"),
        link: "/",
      },
      {
        title: t("ECOSYSTEM_EXPLORE_BIT_LAYER_TITLE"),
        logoUrl: "/images/ecosystem/bit_layer.png",
        text: t("ECOSYSTEM_EXPLORE_BIT_LAYER_TEXT"),
        link: "/",
      },
    ],
  };
};
