name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build react project
        run: npm run build --if-present
        env:
          REACT_APP_DASHBORAD_URL: "https://api.dashboard.pstake.finance"
          REACT_APP_STK_BNB_CONTRACT_ADDRESS: "0xc2E9d07F66A89c44062459A47a0D2Dc038E4fb16"
          REACT_APP_STAKE_POOL_CONTRACT_ADDRESS: "0xC228CefDF841dEfDbD5B3a18dFD414cC0dbfa0D8"
          REACT_APP_BNB_CHAIN_RPC_URL: "https://bsc-mainnet.nodereal.io/v1/9077738996654734a214979c60a7846d"
          REACT_APP_ONE_SIGNAL_APP_ID: "d9ecac74-9446-4df2-9a04-ba68bee2caee"
          REACT_APP_SHIELD_CONTRACT_ADDRESS: "0xb221dd27b05ff07704426d9bbecc4b6b9ab931c4"
          REACT_APP_ENVIRONMENT: "Mainnet"
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "release"
