name: Staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build react project
        run: npm run build --if-present
        env:
          CI: false
          REACT_APP_DASHBORAD_URL: 'https://api.dashboard.pstake.finance'
          REACT_APP_STK_BNB_CONTRACT_ADDRESS: '0xF7CE8444b3b1c62e785a25343a8B4764198A81B8'
          REACT_APP_STAKE_POOL_CONTRACT_ADDRESS: '0x7CdFba1Ee6A8D1e688B4B34A56b62287ce400802'
          REACT_APP_BNB_CHAIN_RPC_URL: 'https://data-seed-prebsc-1-s1.binance.org:8545'
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'staging'
