name: Staging

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build react project
        run: npm run build && npm run export --if-present
        env:
          CI: false
          NEXT_PUBLIC_DASHBORAD_URL: "https://api.dashboard.pstake.finance"
          NEXT_PUBLIC_STK_BNB_CONTRACT_ADDRESS: "0xF7CE8444b3b1c62e785a25343a8B4764198A81B8"
          NEXT_PUBLIC_STAKE_POOL_CONTRACT_ADDRESS: "0x7CdFba1Ee6A8D1e688B4B34A56b62287ce400802"
          NEXT_PUBLIC_BNB_CHAIN_RPC_URL: "https://data-seed-prebsc-1-s1.binance.org:8545"
          NEXT_PUBLIC_ONE_SIGNAL_APP_ID: "d9ecac74-9446-4df2-9a04-ba68bee2caee"
          NEXT_PUBLIC_SHIELD_CONTRACT_ADDRESS: "0xd48096fd351f429bb15eec36c8675fcdef12d499"
          NEXT_PUBLIC_ENVIRONMENT: "Mainnet"
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "staging"
