import {
  VALIDATOR_ANKR,
  VALIDATOR_AVENGERS,
  VALIDATOR_CERTIC,
  VALIDATOR_COINBASE,
  VALIDATOR_DEFIBIT,
  VALIDATOR_FUJI,
  VALIDATOR_LEGEND,
  VALIDATOR_MATH,
  VALIDATOR_NODE_REAL,
  VALIDATOR_TRANCHES,
} from "../../constants/config";

export const validators_list = [
  {
    val_1_name: "Stake Fish",
    val_1_logo: "/images/validators/atom/stakefish.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "SG-1",
    val_2_logo: "/images/validators/atom/sg-1.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Zero Knowledge Validator",
    val_1_logo: "/images/validators/atom/zkv.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Game",
    val_2_logo: "/images/validators/atom/game.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Everstake",
    val_1_logo: "/images/validators/atom/everstake.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Figment",
    val_2_logo: "/images/validators/atom/figment.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Cosmostation",
    val_1_logo: "/images/validators/atom/cosmostation.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "P2P",
    val_2_logo: "/images/validators/atom/p2p.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Chorus One",
    val_1_logo: "/images/validators/atom/chorus.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Multichain Ventures",
    val_2_logo: "/images/validators/atom/multichain.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Citadel One",
    val_1_logo: "/images/validators/atom/citadelone.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Provalidator",
    val_2_logo: "/images/validators/atom/provalidator.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Cephalopod Equipments",
    val_1_logo: "/images/validators/atom/cephalopod.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "StakeLab",
    val_2_logo: "/images/validators/atom/stakelab.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Iqlusion",
    val_1_logo: "/images/validators/atom/iqlusion.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Forbole",
    val_2_logo: "/images/validators/atom/forbole.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Imperator",
    val_1_logo: "/images/validators/atom/imperator.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Blockpower",
    val_2_logo: "/images/validators/atom/blockpower.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Swiss Staking",
    val_1_logo: "/images/validators/atom/swissstaking.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Strangelove-ventures",
    val_2_logo: "/images/validators/atom/stranglove.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "B-Harvest",
    val_1_logo: "/images/validators/atom/b-harvest.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "ChainLayer",
    val_2_logo: "/images/validators/atom/chainlayer.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "ShapeShift DAO",
    val_1_logo: "/images/validators/atom/shapeshift.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Stakecito",
    val_2_logo: "/images/validators/atom/stakecito.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Delga Networks",
    val_1_logo: "/images/validators/atom/delega.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "IRISnet-Bianjie",
    val_2_logo: "/images/validators/atom/irisnet.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "KalpaTech",
    val_1_logo: "/images/validators/atom/kalpatech.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "0base.vc",
    val_2_logo: "/images/validators/atom/0base.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Vortex.live",
    val_1_logo: "/images/validators/atom/vortex.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "PostHuman",
    val_2_logo: "/images/validators/atom/posthuman.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "ATEAM",
    val_1_logo: "/images/validators/atom/ateam.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Umbrella",
    val_2_logo: "/images/validators/atom/umbrella.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "AUDIT.one",
    val_1_logo: "/images/validators/atom/audit.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Simply Staking",
    val_2_logo: "/images/validators/atom/simplystaking.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "S16 Research Ventures",
    val_1_logo: "/images/validators/atom/s16.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Notional",
    val_2_logo: "/images/validators/atom/notional.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "01 node",
    val_1_logo: "/images/validators/atom/01node.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Cypher Core",
    val_2_logo: "/images/validators/atom/cyphercore.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "EZstaking",
    val_1_logo: "/images/validators/atom/ezstaking.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "We staking",
    val_2_logo: "/images/validators/atom/westaking.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Stakewolle",
    val_1_logo: "/images/validators/atom/stakewolle.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Decentralizehk",
    val_2_logo: "/images/validators/atom/dhk.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Smart Nodes",
    val_1_logo: "/images/validators/atom/smartnodes.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "FreshATOMs.com",
    val_2_logo: "/images/validators/atom/freshatoms.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Polkachu.com",
    val_1_logo: "/images/validators/atom/polkachu.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Blockdaemon",
    val_2_logo: "/images/validators/atom/blockdaemon.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Witval",
    val_1_logo: "/images/validators/atom/witval.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Stakin",
    val_2_logo: "/images/validators/atom/stakin.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Smart Stake",
    val_1_logo: "/images/validators/atom/smartstake.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Citizen Cosmos",
    val_2_logo: "/images/validators/atom/citizencosmos.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "StakeWithUs",
    val_1_logo: "/images/validators/atom/stakewithus.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Stakely.io",
    val_2_logo: "/images/validators/atom/stakely.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "AIR DROP STATION",
    val_1_logo: "/images/validators/atom/airdropstation.sv",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "in3s.com",
    val_2_logo: "/images/validators/atom/in3s.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "commercio.network",
    val_1_logo: "/images/validators/atom/commercio.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Easy 2 Stake",
    val_2_logo: "/images/validators/atom/easy2stake.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "jabbey",
    val_1_logo: "/images/validators/atom/jabbey.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "Blocks United",
    val_2_logo: "/images/validators/atom/blocksunited.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "CryptoCrew Validators",
    val_1_logo: "/images/validators/atom/cryptocrew.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "blockscape",
    val_2_logo: "/images/validators/atom/blockspace.svg",
    val_2_url: VALIDATOR_MATH,
  },
  {
    val_1_name: "Ping.pub",
    val_1_logo: "/images/validators/atom/pingpub.svg",
    val_1_url: VALIDATOR_LEGEND,
    val_2_name: "stake.systems",
    val_2_logo: "/images/validators/atom/stakesystems.svg",
    val_2_url: VALIDATOR_MATH,
  },
];
